### ISSUE TITLE
[KERN-3] patch v2.0.2 for initsubtract sort and compute scripts

### ISSUE THREAD

**Issue by ygrange** [kernsuite-debian/prefactor#4]
There is an issue with the two initsubtract sort and compute scripts. This makes them essentially crash in some cases.   

This commit patch makes it work again:
https://github.com/lofar-astron/prefactor/commit/dd0ec767ca4b20206155bb5100455697c712877b.patch 

Could it be applied to KERN-3?

**Comment by ygrange** [comment]
(maybe would've been nice to also give you a link to the actual commit: https://github.com/lofar-astron/prefactor/commit/dd0ec767ca4b20206155bb5100455697c712877b ; saves you from copy-pasting and editing the link...).

**Comment by gijzelaerr** [comment]
moving this issue to https://github.com/kernsuite/packaging/issues/146
